name: test_worldline
version: 1.0.0+1
publish_to: none
description: Worldline
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  get: 4.6.5
  sqflite: ^2.2.8+2
  dio: ^5.1.2
  flutter:
    sdk: flutter

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

